
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { SessionProvider, getSession, useSession } from 'next-auth/react'
import { Toaster } from '@/components/ui/sonner';
import Header from './components/header/header';
import { Sidebar } from './components/sidebar/SideNavbar';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'RD Realty Development Corporation',
  description: 'Generated by create next app',
}

export default async function StaffLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
      <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Toaster />
        <Header />
        <Sidebar />
        <main className='mx-5 mt-16 sm:ml-[300px] sm:mt-3'>{children}</main>
      </body>
      </html>
  )
}
